Fix ImportError (PY3 from cornice)
Fix ImportError "Cannot import name 'PY3'" because it was removed from
cornice and also created a dummy app to get the tests running again
(also was removed from cornice).